version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME="My Dockerized App"
      - GMAIL_USER=XXXXXXXX
      - GMAIL_PASS=XXXXXXXX
      
